### ISSUE TITLE
gcache.page. files not removed fast enough when many big transactions happen in short time

### ISSUE THREAD

**Issue by PrzemekMalkowski** [codership/galera#317]
When many huge transactions happen in short time, new gcache page files are added, but it may lead to a situation that too much disk space is used, as these are not removed immediately.
An example set of gcache files after running couple of large transactions, executed in parallel from two nodes (one transaction per one node at a time):
-rw-------. 1 mysql mysql 129M Aug 12 09:36 galera.cache
-rw-------  1 mysql mysql 370M Aug 12 09:32 gcache.page.000000
-rw-------  1 mysql mysql 370M Aug 12 09:46 gcache.page.000001
-rw-------  1 mysql mysql 370M Aug 12 09:52 gcache.page.000002
-rw-------  1 mysql mysql 247M Aug 12 09:57 gcache.page.000003

After some time the oldest files are removed, but sometimes it may be too late for some specific workloads. 
Is it possible to have the removal rate configured somehow?

I noticed also that any node restart seems to trigger faster gcache files removal on other nodes. I wonder if there is any similar workaround to trigger faster cleanup without the need to restart nodes?

**Comment by ayurchen** [comment]
Przemek,

Let me guess: this workload has relatively few rows but huge row images?

Gcache pages cannot be removed faster than the certification index is purged, because writesets in those pages are referenced by certification index.

Certification index purging is controlled by an algorithm which depends on the certification index size, but is also rather non-trivial since it also involves writeset certification ranges, which cannot be predicted and so on.

What happens on node shutdown is that in Galera < 3.x slave queue is flushed and certification index is reset on every configuration change (something similar to checkpoint in InnoDB). So, for example, joining garbd to the cluster will trigger this as well. However it also means that some of ongoing transactions will be rolled back and clients will probably see some short term stall while slave queue is being flushed.

Another option is certification index flooding by introducing dummy transaction that modifies ~1K rows. (E.g. creating a stub InnoDB table and inserting (or updating, if this needs to be done frequently) 1K rows) This won't guarantee immediate certification index purge (due to non-triviality mentioned above), but should considerably hasten it.

**Comment by PrzemekMalkowski** [comment]
Indeed, for a typical workloads with transactions affecting lot of relatively small rows, this problem seems to be not so much visible. However when you update just a single, but large row, you are in trouble very soon. Ideally Galera should take care about total size of cache page files and remove them quicker when approaching some configurable limit or if close to filling the disk space.
Here is a quickly reproducible test case:

perl -e '$s="$s\x31"; for my $i (0..26214400) { print $s; } ' > /tmp/blob

use test
CREATE TABLE `blob1` (
  `id` int(11) NOT NULL,
  `a` tinyint(4) DEFAULT NULL,
  `big` longblob,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB;
 insert into blob1 values (1,1,LOAD_FILE('/tmp/blob'));

for i in {1..50}; do mysql test -e "UPDATE blob1 SET a=$i,big=LOAD_FILE('/tmp/blob')"; done

**Comment by philip-galera** [comment]
The fix in 3.12 seems to have been sufficient, so closing this bug.
