### ISSUE TITLE
Memcached support?

### ISSUE THREAD

**Issue by siliconalchemy** [codership/galera#371]
Galera doesn't seem to support replication when storing values through the memcached interface.  The documentation indicates that it uses RBR logging which I thought should indicate it should be supported by galera - or does galera pick up RBR before the memcached inserts it?

Someone indicated they had it working without innodb_api_enable_binlog enabled:
https://bugs.launchpad.net/percona-xtradb-cluster/+bug/1254126
But I've tried this with no success.

Is this just a known limitation of galera and it won't work now or in the near future?

**Comment by ayurchen** [comment]
As you can see from the aforementioned bug title "MySQL-wsrep does not replicate Innodb memcached plugin writes" it has nothing to do with Galera and is not its limitation. Simply nobody has integrated memcached plugin with wsrep API.

**Comment by siliconalchemy** [comment]
Please excuse me, I know little about the internals of these systems and don't really understand the difference between galera and wsrep (galera is one implementation of wsrep?).  Should this question be asked on https://launchpad.net/wsrep/ instead?

**Comment by ayurchen** [comment]
Galera is an abstract replication library. It knows nothing about MySQL, let alone its memcached plugin. It just happens so that memcached plugin has a separate execution path in MySQL and does not call necessary wsrep calls by default. It needs to be ported individually.

As for the question - if it is a feature request, it can be reported in https://github.com/codership/mysql-wsrep - cause it is what you want to get fixed.

**Comment by siliconalchemy** [comment]
So requested:
https://github.com/codership/mysql-wsrep/issues/230

Thanks for your fantastic work :)
