### ISSUE TITLE
Replication deadlock on insert against table with foreign key constraint

### ISSUE THREAD

**Issue by rolandshoemaker** [codership/galera#491]
While testing [google/trillian](https://github.com/google/trillian) with XtraDB (`5.7.19-17-57` with wsrep_provider_version `3.22(r8678538)`) in a two node cluster I've run into a deadlock issue while replicating inserts into a table with a foreign key constraint which appears to be a bug. The issue doesn't seem to appear when using `3.20(r7e383f7)`.

The following golang snippet reliably recreates the issue:
```
package main

import (
	"crypto/rand"
	"database/sql"
	"log"

	_ "github.com/go-sql-driver/mysql"
)

// Setup:
//   CREATE DATABASE testing;
//   CREATE TABLE testing.exampleRef (a bigint(20) NOT NULL, PRIMARY KEY (a));
//   INSERT INTO testing.exampleRef (a) VALUES (0);
//   CREATE TABLE testing.example (a bigint(20) NOT NULL, b varbinary(255) NOT NULL, PRIMARY KEY (a, b), CONSTRAINT cons FOREIGN KEY (a) REFERENCES testing.exampleRef (a) ON DELETE CASCADE);

func execute(host string) {
	db, err := sql.Open("mysql", host)
	if err != nil {
		panic(err)
	}

	for {
		r := make([]byte, 8)
		_, err = rand.Read(r[:])
		if err != nil {
			panic(err)
		}
		_, err = db.Exec("INSERT INTO example(a,b) VALUES(0,?)", r)
		if err != nil {
			log.Println(err)
		}
	}
}

func main() {
	go execute("root@tcp(node-a:3306)/testing")
	go execute("root@tcp(node-b:3306)/testing")
	f := make(chan bool, 1)
	<-f
}
```

For those that don't read golang this simply runs two loops in parallel which each execute an insert into the table that contains the foreign key constraint on each of the two cluster nodes, the value of the constrained column is stable (`0`) and the second half of the primary key is simply a random 8 byte value.

This bug manifests as every (or every other) insert or so on one of the nodes failing with the error `Error 1213: Deadlock found when trying to get lock; try restarting transaction`, every few seconds the bad node seems to flip.

**Comment by temeo** [comment]
Hi,

Unfortunately this is expected behavior in current version. Inserts to 'example' table need to have exclusive certification key matching to 'exampleRef' table record in order to detect conflicts with operations to 'exampleRef' table, such as row deletion. This exclusive key will make inserts to 'example' table to conflict. Relaxing the need to have exclusive keys for inserts would require significant changes to certification algorithm, which are not in plans right now.

As a workaround, please try to direct inserts to 'example' table to single node. If that is not possible and inserts are not part of a transaction, increasing the value of wsrep_retry_autocommit might make them to fail less often: http://galeracluster.com/documentation-webpages/mysqlwsrepoptions.html#wsrep-retry-autocommit.

**Comment by rolandshoemaker** [comment]
Thanks for the response! This is a bummer, it looks like we'll have to do single node inserts since we require heavy use of foreign key constraints for this application which is a shame since the main reason for using galera in the first place was that it provided multi-master support.

**Comment by temeo** [comment]
The fix for this issue will be included in
* Galera 3.24
* MySQL-wsrep 5.5.61-25.24, 5.6.41-25.23, 5.7.23-25.15

**Comment by yangbaik** [comment]
Is this fix related with MDEV-15227?

**Comment by buttflattery** [comment]
this issue still persist when using foreign key constraints and doing bulk inserts in the child table locs the parent table which further locks other queries depending on the parent table and eventually falling with wsrep execution lock wait timeout
